[package]
name = "ctrlsys-toolbox-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
eframe = "0.31.1"
egui_extras = "0.31.1"
egui_plot = "0.32.1"
ndarray = "0.16.1"
ndarray-linalg = "0.17.0"
num = "0.4.3"
